### ISSUE TITLE
Forecast on compatibility with .NET 8 and Android

### ISSUE THREAD

**Issue by shesellsanctuary** [0xc3u/Plugin.Maui.Health#1]
Hello!

First of all, hank you very much for the plugin!

I would like to know if there is an intent to upgrade it to .NET 8 in the near future and add Android compatibility as well. .NET 8 and MAUI are still in early stages, I understand, but in my company we are looking forward to using these technologies soon and this plugin would help a lot. 

best regards

**Comment by 0xc3u** [comment]
Hello,

Thank you for reaching out and for your kind words about our plugin.

We are excited to share that we are indeed planning to migrate our plugin to .NET 8, aligning with the latest advancements in the .NET ecosystem. This upgrade is on our roadmap, and we are working diligently to ensure a smooth transition.

Regarding Android compatibility, I'm pleased to inform you that our upcoming update will include the provision of health data for the Android platform. This addition is aimed at enhancing the utility and reach of our plugin across different devices.

While I cannot provide a specific timeline at the moment, please rest assured that these updates are a significant part of our development plan.
We are as enthusiastic as you are about embracing these new technologies and will keep our users informed about our progress.

Thank you for your interest in our plugin and for considering it for your company's future projects. We look forward to contributing to your success with these new technologies.

Best regards
