### ISSUE TITLE
ReadLatestAsync can be interpreted incorrectly 

### ISSUE THREAD

**Issue by ttmher** [0xc3u/Plugin.Maui.Health#2]
Currently, when we call ReadLatestAsync, we get the latest value within a given date range (with no further information).

However, ReadLatestAsync can also be understood as getting the latest available value.

Please add a new function to get the latest available value.
e.g. `Task<Sample> ReadLatestAvailableAsync(HealthParameter healthParameter, string unit)`
By returning a Sample here, we can get the information about when the data was recorded.

**Comment by 0xc3u** [comment]
Hello ttmher

Thank you for your feedback, we added the method you suggested "ReadLatestAvailableAsync" in the version "v1.0.0-preview8".

`
Sample bodyHeigth= await Health.ReadLatestAvailableAsync(HealthParameter.Height, Units.Length.Centimeters);
`
